name: flutter_line_sdk
description: A Flutter plugin for using the LINE SDKs with Dart in Flutter apps.
version: 1.1.0
author: LINE Corporation <dl_line_sdk_pub@linecorp.com>
homepage: https://developers.line.biz/
repository: https://github.com/line/flutter_line_sdk/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.linecorp.flutter_line_sdk
    pluginClass: FlutterLineSdkPlugin
